### PR TITLE
Only check for pwned password if pwned_password_check_on_sign_in is set to true

### PR DESCRIPTION
**Pull request by jpawlyn**
Avoid calls to haveibeenpwned API on user login by default for when we don't want to warn existing users that their password is compromised.

### CODE REVIEW

**Comment by michaelbanfield** [comment]
Thanks for the PR.

To clarify, could users just not override after_sign_in_path_for to avoid this call?

**Comment by jpawlyn** [comment]
I don't think so. The call to `password_pwned?` gets made in the [warden hook](https://github.com/michaelbanfield/devise-pwned_password/blob/master/lib/devise/pwned_password/hooks/pwned_password.rb#L5) whereas the `after_sign_in_path_for` method just calls for the result of the pwned check.

**Comment by michaelbanfield** [comment]
Ah so the API call is always made but ignored if the after_sign_in_path_for is not set.

Thanks for this change. I’d like to keep the default behaviour the same so existing consumers don’t have to enable the config, could you change the config to default to true?

Otherwise looks good.

**Comment by jpawlyn** [comment]
Yup, no problem. I've switched the default to true and updated the README.

**Pull request merged**
